export {getTag} from "./getTag";
export {isArray} from "./isArray";
export {isBoolean} from "./isBoolean";
export {isNumber} from "./isNumber";
export {isNull} from "./isNull";
export {isObject} from "./isObject";
export {isString} from "./isString";
export {isUndefined} from "./isUndefined";
export {isFunction} from "./isFunction";
